# Generated by Django 3.2.25 on 2025-08-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='countView',
        ),
        migrations.AddField(
            model_name='post',
            name='countView',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
