# Generated by Django 3.2.25 on 2025-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250830_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='value',
            field=models.CharField(default=1, max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
